// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using pypSln.App.persistencia;

namespace pypSln.persistencia.Migrations
{
    [DbContext(typeof(appContext))]
    [Migration("20220922042855_inicio")]
    partial class inicio
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("pypSln.App.dominio.historiaClinica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("Fecha_registro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Formula")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id_ovino")
                        .HasColumnType("int");

                    b.Property<int>("Id_propietario")
                        .HasColumnType("int");

                    b.Property<int>("Id_registro")
                        .HasColumnType("int");

                    b.Property<int>("Id_veterinario")
                        .HasColumnType("int");

                    b.Property<string>("Recomendaciones")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("historiaClinica");
                });

            modelBuilder.Entity("pypSln.App.dominio.ovino", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("especie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("raza")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sexo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ovino");
                });

            modelBuilder.Entity("pypSln.App.dominio.persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("persona");

                    b.HasDiscriminator<string>("Discriminator").HasValue("persona");
                });

            modelBuilder.Entity("pypSln.App.dominio.registroHistoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_ovino")
                        .HasColumnType("int");

                    b.Property<int>("Id_propietario")
                        .HasColumnType("int");

                    b.Property<int>("Id_veterinario")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("registroHistoria");
                });

            modelBuilder.Entity("pypSln.App.dominio.visitapyp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Fre_cardiaca")
                        .HasColumnType("float");

                    b.Property<double>("Fre_respiratoria")
                        .HasColumnType("float");

                    b.Property<int>("Id_ovino")
                        .HasColumnType("int");

                    b.Property<int>("Id_propietario")
                        .HasColumnType("int");

                    b.Property<int>("Id_veterinario")
                        .HasColumnType("int");

                    b.Property<string>("Recomendaciones")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Temperatura")
                        .HasColumnType("float");

                    b.Property<DateTime>("fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("formula")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("peso")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("visitapyp");
                });

            modelBuilder.Entity("pypSln.App.dominio.propietario", b =>
                {
                    b.HasBaseType("pypSln.App.dominio.persona");

                    b.HasDiscriminator().HasValue("propietario");
                });

            modelBuilder.Entity("pypSln.App.dominio.veterinario", b =>
                {
                    b.HasBaseType("pypSln.App.dominio.persona");

                    b.Property<string>("TarjetaProfesional")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("veterinario");
                });
#pragma warning restore 612, 618
        }
    }
}
